title: Run MicroPython programs on your Raspberry Pi Pico when disconnected from your computer
hero_image: images/banner.png
description: run-python-main-pico description
version: 4
listed: false
copyedit: false
last_tested: "2022-02-08"
steps:
  - title: Automatically run a program using main.py

